import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';

export enum MaintenanceType {
  WATER_CHANGE = 'water_change',
  FILTER_REPLACEMENT = 'filter_replacement',
  HARVEST = 'harvest',
  NUTRIENT_REFILL = 'nutrient_refill',
  CALIBRATION = 'calibration',
  OTHER = 'other',
}

@Entity('maintenance_logs')
export class MaintenanceLog {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'device_id' })
  @Index()
  deviceId: string;

  @Column({ type: 'enum', enum: MaintenanceType })
  type: MaintenanceType;

  @Column({ nullable: true })
  notes: string;

  // Who logged it - null when auto-generated by the system rather than a user action.
  @Column({ name: 'logged_by_user_id', type: 'uuid', nullable: true })
  loggedByUserId: string | null;

  @Column({ name: 'performed_at', type: 'timestamptz' })
  performedAt: Date;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}
